# ------------------------------------------------------------------------------
# Copyright (c) Microsoft
# Licensed under the MIT License.
# Written by Bin Xiao (Bin.Xiao@microsoft.com)
# Modified by Ke Sun (sunk@mail.ustc.edu.cn), Tianheng Cheng(tianhengcheng@gmail.com)
# ------------------------------------------------------------------------------

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from yacs.config import CfgNode as CN


_C = CN()

_C.OUTPUT_DIR = 'output'
_C.LOG_DIR = 'log'
_C.GPUS = (0, 1, 2, 4)
_C.WORKERS = 16
_C.PRINT_FREQ = 20
_C.AUTO_RESUME = False
_C.PIN_MEMORY = True

# Cudnn related params
_C.CUDNN = CN()
_C.CUDNN.BENCHMARK = False
_C.CUDNN.DETERMINISTIC = False
_C.CUDNN.ENABLED = True

# common params for NETWORK
_C.MODEL = CN()
_C.MODEL.NAME = 'hrnet'
_C.MODEL.INIT_WEIGHTS = True
_C.MODEL.PRETRAINED = ''
_C.MODEL.NUM_JOINTS = 17
_C.MODEL.TARGET_TYPE = 'Gaussian'
_C.MODEL.IMAGE_SIZE = [256, 256]  # width * height
_C.MODEL.HEATMAP_SIZE = [64, 64]  # width * height
_C.MODEL.SIGMA = 1.5

# High-Resoluion Net
_C.MODEL.EXTRA = CN()
_C.MODEL.EXTRA.FINAL_CONV_KERNEL = 1

_C.MODEL.EXTRA.STAGE2 = CN()
_C.MODEL.EXTRA.STAGE2.STG_ID = 2
_C.MODEL.EXTRA.STAGE2.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE2.NUM_BRANCHES = 2
_C.MODEL.EXTRA.STAGE2.NUM_BLOCKS = [4, 4]
_C.MODEL.EXTRA.STAGE2.NUM_CHANNELS = [18, 36]
_C.MODEL.EXTRA.STAGE2.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE2.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE2.BETA_IN_CHANNELS = []
_C.MODEL.EXTRA.STAGE2.BETA_BRANCH_ID = []
_C.MODEL.EXTRA.STAGE2.BETA_WEIGHTS_ID = [ 0, 1, 2, 3]
_C.MODEL.EXTRA.STAGE2.BETA_WEIGHTS = []
_C.MODEL.EXTRA.STAGE2.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE2.FUSE_METHOD = 'SUM'

_C.MODEL.EXTRA.STAGE3 = CN()
_C.MODEL.EXTRA.STAGE3.STG_ID = 3
_C.MODEL.EXTRA.STAGE3.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE3.NUM_BRANCHES = 3
_C.MODEL.EXTRA.STAGE3.NUM_BLOCKS = [4, 4, 4]
_C.MODEL.EXTRA.STAGE3.NUM_CHANNELS = [18, 36, 72]
_C.MODEL.EXTRA.STAGE3.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE3.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE3.BETA_IN_CHANNELS = [[18, 36]]
_C.MODEL.EXTRA.STAGE3.BETA_BRANCH_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE3.BETA_WEIGHTS_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE3.BETA_WEIGHTS = [[1, 1]]
_C.MODEL.EXTRA.STAGE3.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE3.FUSE_METHOD = 'SUM'

_C.MODEL.EXTRA.STAGE4 = CN()
_C.MODEL.EXTRA.STAGE4.STG_ID = 4
_C.MODEL.EXTRA.STAGE4.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE4.NUM_BRANCHES = 4
_C.MODEL.EXTRA.STAGE4.NUM_BLOCKS = [4, 4, 4, 4]
_C.MODEL.EXTRA.STAGE4.NUM_CHANNELS = [18, 36, 72, 144]
_C.MODEL.EXTRA.STAGE4.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE4.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE4.BETA_IN_CHANNELS = [[18, 36]]
_C.MODEL.EXTRA.STAGE4.BETA_BRANCH_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE4.BETA_WEIGHTS_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE4.BETA_WEIGHTS = [[1, 1]]
_C.MODEL.EXTRA.STAGE4.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE4.FUSE_METHOD = 'SUM'

_C.MODEL.EXTRA.STAGE5 = CN()
_C.MODEL.EXTRA.STAGE5.STG_ID = 5
_C.MODEL.EXTRA.STAGE5.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE5.NUM_BRANCHES = 4
_C.MODEL.EXTRA.STAGE5.NUM_BLOCKS = [4, 4, 4, 4]
_C.MODEL.EXTRA.STAGE5.NUM_CHANNELS = [18, 36, 72, 144]
_C.MODEL.EXTRA.STAGE5.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE5.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE5.BETA_IN_CHANNELS = [[18, 36]]
_C.MODEL.EXTRA.STAGE5.BETA_BRANCH_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE5.BETA_WEIGHTS_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE5.BETA_WEIGHTS = [[1, 1]]
_C.MODEL.EXTRA.STAGE5.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE5.FUSE_METHOD = 'SUM'

_C.MODEL.EXTRA.STAGE6 = CN()
_C.MODEL.EXTRA.STAGE6.STG_ID = 6
_C.MODEL.EXTRA.STAGE6.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE6.NUM_BRANCHES = 4
_C.MODEL.EXTRA.STAGE6.NUM_BLOCKS = [4, 4, 4, 4]
_C.MODEL.EXTRA.STAGE6.NUM_CHANNELS = [18, 36, 72, 144]
_C.MODEL.EXTRA.STAGE6.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE6.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE6.BETA_IN_CHANNELS = [[18, 36]]
_C.MODEL.EXTRA.STAGE6.BETA_BRANCH_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE6.BETA_WEIGHTS_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE6.BETA_WEIGHTS = [[1, 1]]
_C.MODEL.EXTRA.STAGE6.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE6.FUSE_METHOD = 'SUM'

_C.MODEL.EXTRA.STAGE7 = CN()
_C.MODEL.EXTRA.STAGE7.STG_ID = 7
_C.MODEL.EXTRA.STAGE7.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE7.NUM_BRANCHES = 4
_C.MODEL.EXTRA.STAGE7.NUM_BLOCKS = [4, 4, 4, 4]
_C.MODEL.EXTRA.STAGE7.NUM_CHANNELS = [18, 36, 72, 144]
_C.MODEL.EXTRA.STAGE7.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE7.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE7.BETA_IN_CHANNELS = [[18, 36]]
_C.MODEL.EXTRA.STAGE7.BETA_BRANCH_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE7.BETA_WEIGHTS_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE7.BETA_WEIGHTS = [[1, 1]]
_C.MODEL.EXTRA.STAGE7.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE7.FUSE_METHOD = 'SUM'

_C.MODEL.EXTRA.STAGE8 = CN()
_C.MODEL.EXTRA.STAGE8.STG_ID = 8
_C.MODEL.EXTRA.STAGE8.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE8.NUM_BRANCHES = 4
_C.MODEL.EXTRA.STAGE8.NUM_BLOCKS = [4, 4, 4, 4]
_C.MODEL.EXTRA.STAGE8.NUM_CHANNELS = [18, 36, 72, 144]
_C.MODEL.EXTRA.STAGE8.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE8.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE8.BETA_IN_CHANNELS = [[18, 36]]
_C.MODEL.EXTRA.STAGE8.BETA_BRANCH_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE8.BETA_WEIGHTS_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE8.BETA_WEIGHTS = [[1, 1]]
_C.MODEL.EXTRA.STAGE8.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE8.FUSE_METHOD = 'SUM'

_C.MODEL.EXTRA.STAGE9 = CN()
_C.MODEL.EXTRA.STAGE9.STG_ID = 9
_C.MODEL.EXTRA.STAGE9.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE9.NUM_BRANCHES = 4
_C.MODEL.EXTRA.STAGE9.NUM_BLOCKS = [4, 4, 4, 4]
_C.MODEL.EXTRA.STAGE9.NUM_CHANNELS = [18, 36, 72, 144]
_C.MODEL.EXTRA.STAGE9.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE9.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE9.BETA_IN_CHANNELS = [[18, 36]]
_C.MODEL.EXTRA.STAGE9.BETA_BRANCH_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE9.BETA_WEIGHTS_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE9.BETA_WEIGHTS = [[1, 1]]
_C.MODEL.EXTRA.STAGE9.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE9.FUSE_METHOD = 'SUM'

_C.MODEL.EXTRA.STAGE10 = CN()
_C.MODEL.EXTRA.STAGE10.STG_ID = 9
_C.MODEL.EXTRA.STAGE10.NUM_MODULES = 1
_C.MODEL.EXTRA.STAGE10.NUM_BRANCHES = 4
_C.MODEL.EXTRA.STAGE10.NUM_BLOCKS = [4, 4, 4, 4]
_C.MODEL.EXTRA.STAGE10.NUM_CHANNELS = [18, 36, 72, 144]
_C.MODEL.EXTRA.STAGE10.RETAINED_BLOCKS = [1, 1, 1, 1]
_C.MODEL.EXTRA.STAGE10.BLOCKS_ID = []
_C.MODEL.EXTRA.STAGE10.BETA_IN_CHANNELS = [[18, 36]]
_C.MODEL.EXTRA.STAGE10.BETA_BRANCH_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE10.BETA_WEIGHTS_ID = [[0, 1]]
_C.MODEL.EXTRA.STAGE10.BETA_WEIGHTS = [[1, 1]]
_C.MODEL.EXTRA.STAGE10.BLOCK = 'BASIC'
_C.MODEL.EXTRA.STAGE10.FUSE_METHOD = 'SUM'

# DATASET related params
_C.DATASET = CN()
_C.DATASET.ROOT = ''
_C.DATASET.DATASET = 'AFLW'
_C.DATASET.TRAINSET = ''
_C.DATASET.TESTSET = ''
_C.DATASET.INPUT_SIZE = (3, 256, 256)

# training data augmentation
_C.DATASET.FLIP = True
_C.DATASET.SCALE_FACTOR = 0.25
_C.DATASET.ROT_FACTOR = 30

# train
_C.TRAIN = CN()

_C.TRAIN.LR_FACTOR = 0.1
_C.TRAIN.LR_STEP = [30, 50]
_C.TRAIN.LR = 0.0001

_C.TRAIN.OPTIMIZER = 'adam'
_C.TRAIN.MOMENTUM = 0.0
_C.TRAIN.WD = 0.0
_C.TRAIN.NESTEROV = False

_C.TRAIN.BEGIN_EPOCH = 0
_C.TRAIN.END_EPOCH = 60

_C.TRAIN.RESUME = True
_C.TRAIN.LOAD_BETA = ''
_C.TRAIN.CHECKPOINT = ''

_C.TRAIN.BATCH_SIZE_PER_GPU = 16
_C.TRAIN.SHUFFLE = True

# testing
_C.TEST = CN()

# size of images for each device
_C.TEST.BATCH_SIZE_PER_GPU = 32


def update_config(cfg, args):
    cfg.defrost()
    cfg.merge_from_file(args.cfg)
    cfg.freeze()


if __name__ == '__main__':
    import sys
    with open(sys.argv[1], 'w') as f:
        print(_C, file=f)
